### ISSUE TITLE
Add --no-open flag to develop / serve tasks.

### ISSUE THREAD

**Issue by jameshoward** [plumpdigital/generator-plump-webapp#14]
Prevent the auto-opening of the browser. Useful if you just need to reload the server and already have the served content in a browser window.

**Comment by JamesMD** [comment]
@jameshoward, doesn't this desired behaviour happen now? As in, when we run `gulp develop`, it will use the current window with `localhost:9000`, right? Or do we mean when we run the command, stay in the CLI rather than switching to the browser window?

**Comment by jameshoward** [comment]
In one project I had an option so you could do something like:

`gulp develop --no-open`

That switch prevents the call to open the site in the browser.

Probably not needed any more because it was really only useful when `gulp develop` bombed out because of SCSS errors.
