### ISSUE TITLE
Add config for SVG image minification to not break Sketch SVGs

### ISSUE THREAD

**Issue by jameshoward** [plumpdigital/generator-plump-webapp#30]
The SVGO module seems to break paths on Sketch-exported SVGs. This can be fixed by turning off `applyTransforms` in the `convertPathData` plugin:

    var imageminPipe = config.minifyImages ? imagemin({
		optimizationLevel : 3,
		progressive : true,
		interlaced : true,
		svgoPlugins : [
			{ convertPathData : {
				applyTransforms: false /* [1] */
			}}
		]
	}) : gutil.noop(); /* [2] */

**Comment by jameshoward** [comment]
No longer required because we can just update gulp imagemin instead.

However, a bug with masks remains (https://github.com/svg/svgo/issues/217) that can be fixed with:

```
svgoPlugins : [
    {
        removeUnknownsAndDefaults: false
    }
]
```

So we should add this instead.

**Comment by JamesMD** [comment]
@jameshoward, done in commit #42.
