### ISSUE TITLE
Update relevant NPM module versions in generated package.json

### ISSUE THREAD

**Issue by jameshoward** [plumpdigital/generator-plump-webapp#31]
- Review list of packages against their current version
- Increase version numbers to latest if the *major* version has changed (e.g. change ^0.5.0 to ^1.0.2)
- Keep the use of ^ so we always get the latest of the same major version

**Comment by JamesMD** [comment]
This is now done in the latest pull request.

**Comment by JamesMD** [comment]
@jameshoward done in commit #35.
