### ISSUE TITLE
Check whether we can update to latest Gulp version

### ISSUE THREAD

**Issue by jameshoward** [plumpdigital/generator-plump-webapp#32]
We are currently locking Gulp to v3.7.0 because of an issue with livereload in 3.8.0. We narrowed it down to it using an updated version of vinyl-fs that seemed to have an issue with watching directories. Livereload wasn't being informed of changes so wasn't working.

**Comment by JamesMD** [comment]
So far, from what I tested, this is no longer a persisting issue as of Gulp 3.8.10. 
I should of really tagged this in the commit, but it's done and updated now.

**Comment by JamesMD** [comment]
@jameshoward we can close this issue as we appear to be using the latest Gulp.

**Comment by jameshoward** [comment]
@JamesMD Yes, and LiveReload seems to be fine now. Cheers.
