### ISSUE TITLE
Include SCSS Lint config.

### ISSUE THREAD

**Issue by jonhurrell** [plumpdigital/generator-plump-webapp#45]
https://github.com/plumpdigital/generator-plump-silverstripe/blob/develop/app/templates/src/.scss-lint.yml

**Comment by DevJMD** [comment]
Done by @jonhurrell in commit ffe41d43ad473d9aeb8da7b770b30d76cbab9aba and 28a7a83ae37a73d7e9897e5072bb97f6c9c4caf4.
